services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: nfldb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: portfolioproject123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  dashboard:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:portfolioproject123@postgres:5432/nfldb
    command: bash -c "
      apt-get update -qq && 
      apt-get install -y postgresql-client -qq && 
      pip install streamlit plotly pandas psycopg2-binary && 
      streamlit run src/dashboard/app.py --server.address 0.0.0.0 --server.port 8501
      "

volumes:
  postgres_data: